
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/head/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    # FIXME: optionally install the missing dependencies
    # - name: Install Dependencies
    #   run: zypper --non-interactive install foobar

    # just for easier debugging...
    - name: Inspect Installed Packages
      run: rpm -qa | sort

    # run checks
    - name: Checks
      run: make -C control check

  Package:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/head/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Package Build
      run: yast-ci-ruby -o package

  # downloading the Docker image takes some time so bundling several fast
  # checks into one job avoids that overhead
  Checks:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/head/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: POT Check
      run: rake check:pot

    # FIXME: add additional checks here:
    # - name: Shell Check
    #   run: shellcheck ...
